name: Build and Test

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: '17'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

